### ISSUE TITLE
Rasterizer not handling overlapping outlines.

### ISSUE THREAD

**Issue by asibahi** [alexheretic/ab-glyph#101] opened 2024-04-09 17:56 UTC
Hello.

I am currently using `ab_glyph` with harfbuzz to shape and draw Arabic text with a variable, colored Arabic font. 

When coloring the letters with anything other than black, white, or transparent, I am faced with a number of coloring artifacts that are due to overlapping outlines. You can the reproduction in this fork: https://github.com/asibahi/noor/tree/reproduce_color_artifacts 

I raised with an issue with the font's repo: https://github.com/aliftype/raqq/issues/26 , who pointed out that most of these artifacts are issues with the rasterizer.

I worked around this in the `master` branch by drawing the glyphs with a transparent color, and overlaying it on the needed color. This works for my purposes, but I am hoping for a less hacky solution. Overlapping glyphs are a thing in most Arabic fonts.

**Comment by alexheretic** [comment] 2024-04-09 18:10
Perhaps it's because you are getting >1.0 coverage values and are not handling that? If that's the case try capping the coverage value to 1.

> An alpha coverage value of 0.0 means the pixel is not covered at all by the glyph, whereas a value of 1.0 (or greater) means the pixel is totally covered.

Otherwise, can you provide some steps to reproduce and explain the behaviour you expect vs what you observe.

**Comment by alexheretic** [comment] 2024-04-12 16:49
I'll close this then I think it's solved, please re-open otherwise.

**Closed by alexheretic** 2024-04-12 16:49 UTC
