### ISSUE TITLE
Some otf font parse have no outline glyph?

### ISSUE THREAD

**Issue by TakWolf** [alexheretic/ab-glyph#10] opened 2020-07-12 06:59 UTC
Some otf font parse have no outline glyph.

I make sure the font file is correct, and parse have no error.
But have no glyph.

The otf font from:
https://github.com/adobe-fonts/source-han-sans

font.glyph_count() is 65535,
font.outline_glyph(glyph) return None.

**Comment by TakWolf** [comment] 2020-07-12 07:05
My test code is here:


```rust
use ab_glyph::{FontRef, point};
use ab_glyph::Font;
use image::{ImageBuffer, ImageFormat};

fn main() {
    let font = FontRef::try_from_slice(include_bytes!("../assets/SourceHanSansSC/SourceHanSansSC-Regular.otf")).unwrap();
    println!("glyph_count: {}", font.glyph_count());

    let char = 'A';
    let font_size = 24.0;

    let glyph = font.glyph_id(char)
        .with_scale_and_position(font_size, point(0.0, 0.0));

    if let Some(outlined_glyph) = font.outline_glyph(glyph) {
        let rect = outlined_glyph.px_bounds();
        let mut image_buffer = ImageBuffer::new(
            rect.width().ceil() as u32,
            rect.height().ceil() as u32
        );
        outlined_glyph.draw(|x, y, c| {
            let color = (c.round() * 255.0) as u8; // pixel style
            let pixel = image::Rgba([color, color, color, 255]);
            image_buffer.put_pixel(x, y, pixel);
        });
        image_buffer.save_with_format(format!("out/{}-{}.png", char, font_size), ImageFormat::Png).unwrap();
    } else {
        println!("no glyph");
    }
}

```

result:

glyph_count: 65535
no glyph

**Comment by alexheretic** [comment] 2020-07-12 12:08
Can you raise this as an issue on [ttf-parser](https://github.com/RazrFalcon/ttf-parser). Here's some code that reproduces it using that underlying lib. [font link](https://github.com/adobe-fonts/source-han-sans/raw/release/OTF/SourceHanSansSC.zip).

```rust
use ttf_parser::*;

fn main() {
    let font = Font::from_data(include_bytes!("../SourceHanSansSC-Regular.otf"), 0).unwrap();

    let glyph_index = dbg!(font.glyph_index('A').unwrap());

    dbg!(font.outline_glyph(glyph_index, &mut OutlinePrinter));
}

struct OutlinePrinter;
impl OutlineBuilder for OutlinePrinter {
    fn move_to(&mut self, x: f32, y: f32) {
        eprintln!("move_to {} {}", x, y);
    }
    fn line_to(&mut self, x: f32, y: f32) {
        eprintln!("line_to {} {}", x, y);
    }
    fn quad_to(&mut self, x1: f32, y1: f32, x: f32, y: f32) {
        eprintln!("quad_to {} {} {} {}", x1, y1, x, y);
    }
    fn curve_to(&mut self, x1: f32, y1: f32, x2: f32, y2: f32, x: f32, y: f32) {
        eprintln!("curve_to {} {} {} {} {} {}", x1, y1, x2, y2, x, y);
    }
    fn close(&mut self) {
        eprintln!("close");
    }
}
```

Output:
```
[src/main.rs:6] font.glyph_index('A').unwrap() = GlyphId(34)
[src/main.rs:8] font.outline_glyph(glyph_index, &mut OutlinePrinter) = None
```

**Comment by RazrFalcon** [comment] 2020-07-15 17:04
Just to clarify, this not a bug, but rather an unimplemented feature https://github.com/RazrFalcon/ttf-parser/issues/7

**Comment by RazrFalcon** [comment] 2020-07-16 13:20
Fixed in 0.7.0

@alexheretic  There were some breaking changes. Mainly renaming. Nothing serious.

**Comment by alexheretic** [comment] 2020-07-16 14:16
I've updated the master branch with ttf-parser 0.7, @TakWolf can you retry?

**Comment by TakWolf** [comment] 2020-07-16 16:59
> I've updated the master branch with ttf-parser 0.7, @TakWolf can you retry? I'll publish a release a little later.

It works

**Comment by alexheretic** [comment] 2020-07-17 09:31
[0.2.4](https://github.com/alexheretic/ab-glyph/releases/tag/ab-glyph-0.2.4) is out now. Thanks @RazrFalcon & @TakWolf

**Closed by alexheretic** 2020-07-17 09:31 UTC
